server:
  port: 8081

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:h2:mem:patientdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # Use Flyway for schema management
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    cache-names: patients, patient_search
    redis:
      time-to-live: 24h

jwt:
  secret: your-very-long-and-secure-secret-key-that-is-at-least-256-bits-long
  expiration: 86400 # 24 hours
